//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democracy_Alarm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDB_Entities : DbContext
    {
        public MyDB_Entities()
            : base("name=MyDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KeyValue> KeyValue { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VotingRecords> VotingRecords { get; set; }
    }
}
